=== anaiacob/tema4_ia3-md-/biblioteca.dtd
<!ELEMENT Biblioteca (cartea*)>
<!ELEMENT cartea (titlul, autorul, an_apariție, genul, nr_împrumuturi)>
<!ELEMENT titlul (#PCDATA)>
<!ELEMENT autorul (#PCDATA)>
<!ELEMENT an_apariție (#PCDATA)>
<!ELEMENT genul (#PCDATA)>
<!ELEMENT nr_împrumuturi (#PCDATA)>

=== anaiacob/tema4_ia3-md-/biblioteca.xml
<!DOCTYPE library SYSTEM "C:\Users\anaia\OneDrive\Desktop\biblioteca.dtd">
<?xml version="1.0" encoding="UTF-8"?>

<Biblioteca>
    <cartea>
        <titlul>Mândrie și prejudecată</titlul>
        <autorul>Jane Austen</autorul>
        <an_apariție>1813</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>15</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Charlie și fabrica de ciocolată</titlul>
        <autorul>Roald Dahl</autorul>
        <an_apariție>1964</an_apariție>
        <genul>Carte pentru copii</genul>
        <nr_împrumuturi>8</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>1984</titlul>
        <autorul>George Orwell</autorul>
        <an_apariție>1949</an_apariție>
        <genul>Ficțiune distopică</genul>
        <nr_împrumuturi>20</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Marile speranțe</titlul>
        <autorul>Charles Dickens</autorul>
        <an_apariție>1861</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>12</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Să ucizi o pasăre cântătoare</titlul>
        <autorul>Harper Lee</autorul>
        <an_apariție>1960</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>10</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Frankenstein</titlul>
        <autorul>Mary Shelley</autorul>
        <an_apariție>1818</an_apariție>
        <genul>Literatură gotică</genul>
        <nr_împrumuturi>18</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>La răscruce de vânturi</titlul>
        <autorul>Emily Bronte</autorul>
        <an_apariție>1847</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>14</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Împăratul muștelor</titlul>
        <autorul>William Golding</autorul>
        <an_apariție>1954</an_apariție>
        <genul>Ficțiune pentru tineri</genul>
        <nr_împrumuturi>11</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Vanity Fair</titlul>
        <autorul>William Makepeace Thackeray</autorul>
        <an_apariție>1848</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>16</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Lolita</titlul>
        <autorul>Vladimir Nabokov</autorul>
        <an_apariție>1955</an_apariție>
        <genul>Ficțiune literară</genul>
        <nr_împrumuturi>9</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Jane Eyre</titlul>
        <autorul>Charlotte Bronte</autorul>
        <an_apariție>1847</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>13</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Dune</titlul>
        <autorul>Frank Hebert</autorul>
        <an_apariție>1965</an_apariție>
        <genul>Ficțiune științifico-fantastică</genul>
        <nr_împrumuturi>7</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Marele Gatsby</titlul>
        <autorul>Scott F. Fitzgerald</autorul>
        <an_apariție>1925</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>22</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Tess of the d’Urbervilles</titlul>
        <autorul>Thomas Hardy</autorul>
        <an_apariție>1891</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>11</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Dracula</titlul>
        <autorul>Bram Stoker</autorul>
        <an_apariție>1897</an_apariție>
        <genul>Ficțiune gotică</genul>
        <nr_împrumuturi>17</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>De veghe în lanul de secară</titlul>
        <autorul>JD Salinger</autorul>
        <an_apariție>1951</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>14</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Anna Karenina</titlul>
        <autorul>Lev Tolstoi</autorul>
        <an_apariție>1877</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>19</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Catch-22</titlul>
        <autorul>Joseph Heller</autorul>
        <an_apariție>1961</an_apariție>
        <genul>Literatură absurdă</genul>
        <nr_împrumuturi>10</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Legături periculoase</titlul>
        <autorul>Pierre Choderlos de Laclos</autorul>
        <an_apariție>1782</an_apariție>
        <genul>Roman epistolar</genul>
        <nr_împrumuturi>15</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>O sută de ani de singurătate</titlul>
        <autorul>Gabriel Garcia Marquez</autorul>
        <an_apariție>1967</an_apariție>
        <genul>Realism magic</genul>
        <nr_împrumuturi>21</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Procesul</titlul>
        <autorul>Franz Kafka</autorul>
        <an_apariție>1925</an_apariție>
        <genul>Ficțiune absurdă</genul>
        <nr_împrumuturi>12</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Siddhartha</titlul>
        <autorul>Hermann Hess</autorul>
        <an_apariție>1922</an_apariție>
        <genul>Literatură filozofică</genul>
        <nr_împrumuturi>9</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Contele de Monte Cristo</titlul>
        <autorul>Alexandre Dumas</autorul>
        <an_apariție>1844</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>25</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Cetatea celor o mie de sori</titlul>
        <autorul>Khaled Hosseini</autorul>
        <an_apariție>2007</an_apariție>
        <genul>Ficțiune istorică</genul>
        <nr_împrumuturi>16</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Viața secretă a albinelor</titlul>
        <autorul>Sue Monk Kidd</autorul>
        <an_apariție>2002</an_apariție>
        <genul>Roman contemporan</genul>
        <nr_împrumuturi>11</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Hoțul de cărți</titlul>
        <autorul>Markus Zusak</autorul>
        <an_apariție>2005</an_apariție>
        <genul>Literatură pentru tineret</genul>
        <nr_împrumuturi>19</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Alchimistul</titlul>
        <autorul>Paulo Coelho</autorul>
        <an_apariție>1988</an_apariție>
        <genul>Literatură filozofică</genul>
        <nr_împrumuturi>22</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Aventurile lui Huckleberry Finn</titlul>
        <autorul>Mark Twain</autorul>
        <an_apariție>1885</an_apariție>
        <genul>Literatură pentru tineret</genul>
        <nr_împrumuturi>14</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Cei trei muschetari</titlul>
        <autorul>Alexandre Dumas</autorul>
        <an_apariție>1844</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>18</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Micul prinț</titlul>
        <autorul>Antoine de Saint-Exupery</autorul>
        <an_apariție>1943</an_apariție>
        <genul>Carte pentru copii</genul>
        <nr_împrumuturi>9</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Hobbitul</titlul>
        <autorul>J. R. R. Tolkien</autorul>
        <an_apariție>1937</an_apariție>
        <genul>Ficțiune pentru copii și tineret</genul>
        <nr_împrumuturi>16</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Stăpânul inelelor</titlul>
        <autorul>J. R. R. Tolkien</autorul>
        <an_apariție>1954</an_apariție>
        <genul>Ficțiune pentru copii și tineret</genul>
        <nr_împrumuturi>23</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Bătrânul și marea</titlul>
        <autorul>Ernest Hemingway</autorul>
        <an_apariție>1952</an_apariție>
        <genul>Literatură americană</genul>
        <nr_împrumuturi>13</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Străinul</titlul>
        <autorul>Albert Camus</autorul>
        <an_apariție>1942</an_apariție>
        <genul>Ficțiune existentialistă</genul>
        <nr_împrumuturi>10</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Inferno</titlul>
        <autorul>Dante Alighieri</autorul>
        <an_apariție>1320</an_apariție>
        <genul>Poezie epică</genul>
        <nr_împrumuturi>8</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Don Quixote</titlul>
        <autorul>Miguel de Cervantes</autorul>
        <an_apariție>1605</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>17</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Harry Potter</titlul>
        <autorul>J. K. Rowling</autorul>
        <an_apariție>1997</an_apariție>
        <genul>Fantastic pentru tineret</genul>
        <nr_împrumuturi>27</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>The Games of Thrones</titlul>
        <autorul>George R. R. Martin</autorul>
        <an_apariție>1996</an_apariție>
        <genul>Fantastic epic</genul>
        <nr_împrumuturi>24</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Zece negri mititei</titlul>
        <autorul>Agatha Christie</autorul>
        <an_apariție>1939</an_apariție>
        <genul>Roman polițist</genul>
        <nr_împrumuturi>18</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Poveste despre două orașe</titlul>
        <autorul>Charles Dickens</autorul>
        <an_apariție>1859</an_apariție>
        <genul>Roman clasic</genul>
        <nr_împrumuturi>13</nr_împrumuturi>
    </cartea>
    <cartea>
        <titlul>Cronicile din Narnia</titlul>
        <autorul>C. S. Lewis</autorul>
